### ISSUE TITLE
NaN Errors on Exporting

### ISSUE THREAD

**Issue by Adam8234** [frc2052/FRC-Krawler#11]
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
	at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:300)
	at com.google.gson.Gson.access$000(Gson.java:100)
	at com.google.gson.Gson$3.write(Gson.java:268)
	at com.google.gson.Gson$3.write(Gson.java:254)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:93)
	at com.google.gson.Gson.toJson(Gson.java:605)
	at com.google.gson.Gson.toJsonTree(Gson.java:498)
	at com.google.gson.Gson.toJsonTree(Gson.java:477)
	at com.team2052.frckrawler.database.CompiledMetricValue.compileMetricValues(CompiledMetricValue.java:128)
	at com.team2052.frckrawler.database.CompiledMetricValue.<init>(CompiledMetricValue.java:36)
	at com.team2052.frckrawler.database.MetricCompiler.getCompiledRobot(MetricCompiler.java:81)
	at com.team2052.frckrawler.database.ExportUtil.buildRecord(ExportUtil.java:79)
	at com.team2052.frckrawler.database.ExportUtil.exportEventDataToCSV(ExportUtil.java:51)
	at com.team2052.frckrawler.fragments.server.ExportDialogFragment$ExportToFileSystem.doInBackground(ExportDialogFragment.java:76)
	at com.team2052.frckrawler.fragments.server.ExportDialogFragment$ExportToFileSystem.doInBackground(ExportDialogFragment.java:50)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by Adam8234** [comment]
Fixed in 3.1.0
